prepare-for-braille.xsl: don't use output="html"
`output="html"` creates non-XML entities such as `&nbsp;`.
Use output="xhtml" instead.

The `&nbsp;` entity causes this exception:

```
Traceback (most recent call last):
File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 774,
    in _handle_book_events_thread self.on_book_modified()
File "/opt/produksjonssystem/produksjonssystem/prepare_for_braille.py", line 34,
    in on_book_modified self.on_book()
File "/opt/produksjonssystem/produksjonssystem/prepare_for_braille.py", line 106,
    in on_book html_xml = ElementTree.parse(temp_html).getroot()
File "src/lxml/lxml.etree.pyx", line 3427,
    in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
File "src/lxml/parser.pxi", line 1782,
    in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
File "src/lxml/parser.pxi", line 1808,
    in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
File "src/lxml/parser.pxi", line 1712,
    in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
File "src/lxml/parser.pxi", line 1115,
    in lxml.etree._BaseParser._parseDocFromFile(src/lxml/lxml.etree.c:117533)
File "src/lxml/parser.pxi", line 573,
    in lxml.etree._ParserContext._handleParseResultDoc(src/lxml/lxml.etree.c:110510)
File "src/lxml/parser.pxi", line 683,
    in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
File "src/lxml/parser.pxi", line 613,
    in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
File "", line None
    lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 8266, column 22
```